name=input("Name :")
age=int(input("Age :"))
gender=input("Gender :")
salary=input("Salary :")
city=input("City :")
state=input("State :")

print("Name : ",name)
print("Age : ",age)
print("Gender : ",gender)
print("Salary : ",salary)
print("City : ",city)
print("State : ",state)
