# Generated by Django 3.2.4 on 2021-06-29 17:56
"""Initial"""

# pylint: disable= C0103,E0401
from django.db import migrations, models


# pylint: disable=R0903
class Migration(migrations.Migration):
    """Migration"""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, \
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_ofbirth', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('qualification', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('pan_number', models.CharField(max_length=20)),
            ],
        ),
    ]
