# Generated by Django 3.2.4 on 2021-06-29 17:59
"""Request info"""
# pylint: disable= C0103,E0401
from django.db import migrations, models


# pylint: disable = R0903
class Migration(migrations.Migration):
    """Migrations"""

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_info',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
